# Generated by Django 4.1.2 on 2022-12-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfproject', '0002_board'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='BoardList',
        ),
    ]
